<?xml version="1.0"?>
<package format="3">
  <name>rinbo_ros_bridge</name>
  <version>0.0.1</version>
  <description>ROS2 to gRPC bridge for Rinbo robot</description>
  <maintainer email="b11502018@ntu.edu.tw">shuwei</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rinbo_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

